apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
        - name: messaging-app
          image: messaging_app:2.0
          ports:
            - containerPort: 8000
          command: ["python3"]
          args: ["manage.py", "runserver", "0.0.0.0:8000"]
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: messaging-app-secrets
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: messaging-app-secrets
                  key: DEBUG
