apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
      version: green
  template:
    metadata:
      labels:
        app: messaging-app
        version: green
    spec:
      containers:
        - name: messaging-app
          image: messaging_app:0.1.1
          ports:
            - containerPort: 8000
          command: ["python3"]
          args: ["manage.py", "runserver", "0.0.0.0:8000"]
          env:
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: messaging-app-secrets
                  key: DEBUG
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: messaging-app-secrets
                  key: SECRET_KEY
